pull_request_rules:
  - name: "rebase unreviewed non-release PRs"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "-draft"
    actions:
      rebase:

  - name: "merge non-release SonarCloud-checked PRs with strict rebase"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "-draft"
      - "check-success=SonarCloud Code Analysis"
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: merge

  - name: "merge non-release without-SonarCloud-but-from-dependabot PRs with strict rebase"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "-draft"
      - "author=dependabot[bot]"
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: merge

  - name: "merge release PRs with strict merge"
    conditions:
      - "head~=^(release|hotfix).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "-draft"
    actions:
      merge:
        strict: true
        method: merge

  - name: "delete PR branches after merge"
    conditions:
      - merged
    actions:
      delete_head_branch: {}
