queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "-draft"

pull_request_rules:
  - name: "rebase non-release PRs"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
    actions:
      rebase:

  - name: "merge non-release SonarCloud-checked PRs with strict rebase"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#commits-behind=0"
      - "-draft"
      - "check-success=SonarCloud Code Analysis"
    actions:
      queue:
        name: default
        update_method: rebase

  - name: "merge non-release without-SonarCloud-but-from-dependabot PRs with strict rebase"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#commits-behind=0"
      - "-draft"
      - "author=dependabot[bot]"
    actions:
      queue:
        name: default
        update_method: rebase

  - name: "merge release PRs with strict merge"
    conditions:
      - "head~=^(release|hotfix).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#commits-behind=0"
      - "-draft"
    actions:
      queue:
        name: default
        update_method: rebase

  - name: "delete PR branches after merge"
    conditions:
      - merged
    actions:
      delete_head_branch: {}
