pull_request_rules:
  - name: "rebase unreviewed non-release PRs"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "-draft"
    actions:
      rebase:
        bot_account: rebazer

  - name: "merge non-release PRs with strict rebase"
    conditions:
      - "head~=^(?!(release|hotfix)).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "-draft"
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: merge
        bot_account: rebazer

  - name: "merge release PRs with strict merge"
    conditions:
      - "head~=^(release|hotfix).*$"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "-draft"
    actions:
      merge:
        strict: true
        method: merge
        bot_account: rebazer

  - name: "delete PR branches after merge"
    conditions:
      - merged
    actions:
      delete_head_branch: {}
